# Autogenerated wrapper script for WFA2_jll for aarch64-linux-musl
export libwfa2, libwfa2cpp

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("WFA2")
JLLWrappers.@declare_library_product(libwfa2, "libwfa2.so.0")
JLLWrappers.@declare_library_product(libwfa2cpp, "libwfa2cpp.so.0")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libwfa2,
        "lib/libwfa2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwfa2cpp,
        "lib/libwfa2cpp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
