# Autogenerated wrapper script for WFA2_jll for x86_64-apple-darwin
export libwfa2, libwfa2cpp

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("WFA2")
JLLWrappers.@declare_library_product(libwfa2, "@rpath/libwfa2.dylib")
JLLWrappers.@declare_library_product(libwfa2cpp, "@rpath/libwfa2cpp.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libwfa2,
        "lib/libwfa2.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwfa2cpp,
        "lib/libwfa2cpp.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
